<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-03-01T00:09:27 ICT" name="Suite" finished-at="2023-03-01T00:09:45 ICT" duration-ms="18415">
    <groups>
    </groups>
    <test started-at="2023-03-01T00:09:27 ICT" name="Run On Chrome" finished-at="2023-03-01T00:09:45 ICT" duration-ms="18415">
      <class name="kaopiz.testcases.Exam2">
        <test-method is-config="true" signature="beforeTest()[pri:0, instance:kaopiz.testcases.Exam2@145f66e3]" started-at="2023-03-01T00:09:27 ICT" name="beforeTest" finished-at="2023-03-01T00:09:28 ICT" duration-ms="1222" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method signature="testPlaceholder()[pri:1, instance:kaopiz.testcases.Exam2@145f66e3]" started-at="2023-03-01T00:09:28 ICT" name="testPlaceholder" finished-at="2023-03-01T00:09:33 ICT" duration-ms="5243" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Email placeholder is incorrect! expected [Email] but found [ ]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Email placeholder is incorrect! expected [Email] but found [ ]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at kaopiz.actions.pageObjects.LoginPage.verifyPlaceholder(LoginPage.java:52)
at kaopiz.testcases.Exam2.testPlaceholder(Exam2.java:47)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPlaceholder -->
        <test-method signature="testLoginSuccess()[pri:2, instance:kaopiz.testcases.Exam2@145f66e3]" started-at="2023-03-01T00:09:33 ICT" name="testLoginSuccess" finished-at="2023-03-01T00:09:43 ICT" duration-ms="9773" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLoginSuccess -->
        <test-method is-config="true" signature="afterTest()[pri:0, instance:kaopiz.testcases.Exam2@145f66e3]" started-at="2023-03-01T00:09:43 ICT" name="afterTest" finished-at="2023-03-01T00:09:45 ICT" duration-ms="2128" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- kaopiz.testcases.Exam2 -->
    </test> <!-- Run On Chrome -->
  </suite> <!-- Suite -->
</testng-results>
